<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Форма регистрации</title>
</head>
<body>
<form action="form.php" method="POST" name="users">
    <label>Логин:  <input type="text" name="login" size="30" maxlength="20" /></label><br />
    <br />
    <label>Пароль:<input type="password" name="password" size="30" maxlength="20" /></label><br />
    <br />
    <label><input name="remember" type="checkbox" value="yes" />Запомить</label><br />
    <label><input type="submit" value="Вход" /></label>
    <br />
</form>
</body>
</html>